version: "3.7"

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - .docker/postgres/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
